# Generated by Django 3.2.21 on 2023-09-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230924_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='transfer_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
