# Generated by Django 3.2.21 on 2023-10-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_transfer_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='transfer_time',
        ),
    ]
