# Generated by Django 3.2.21 on 2023-10-13 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_product_transfer_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uuid',
            new_name='product_id',
        ),
    ]
