# Generated by Django 3.2.21 on 2023-10-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_uuid_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='uuid',
        ),
    ]
